### ISSUE TITLE
HSA_STATUS_ERROR_OUT_OF_RESOURCES In rocminfo and no devices in clinfo

### ISSUE THREAD

**Issue by tejasraman** [xuhuisheng/rocm-gfx803#8]
I get the HSA_STATUS_ERROR_OUT_OF_RESOURCES error when I run rocminfo (ROCm 4.5.2) on my computer. A previous install on another drive worked (ROCm 4.5.0) on the same kernel (5.11). When I run clinfo, 0 devices show up under “AMD Accelerated Parallel Processing”.

I have libopenblas and libopenmpi installed already, my PCIe slot supports atomics(no kfd errors). I have the patched ROCBlas and your torch and torchvision. Torch says that there are no CUDA devices(torch treaters HIP as a CUDA device)

OS: Ubuntu 20.04
Kernel: 5.11.0-44-generic
ROCm version: 4.5.2(I originally said 5.2 which does not exist, sorry)

**Comment by xuhuisheng** [comment]
Do you mean ROCm-5.0.2?
ROCm-5.2, even ROCm-5.1 didn't release yet.

**Comment by tejasraman** [comment]
I did try 5.0.2 and apparently torch has no support for it yet, got some amdhip error. Installed 4.5.2 and still having issues

**Comment by xuhuisheng** [comment]
you can try install rocm-4.5.0's kernel and 5.0.2's rocm-dev and rocm-libs.

**Comment by tejasraman** [comment]
So do you mean 4.5.0 ROCm-core? Does this mean having 2 repos installed? Both require hwe 5.11

**Comment by tejasraman** [comment]
Finally got it working with the latest release, sorry,

**Comment by xuhuisheng** [comment]
@tejasraman 
It's weired that I just met HSA_STATUS_ERROR_OUT_OF_RESOURCES on my gfx803 and ubuntu-20.04.4 and hashwell with ROCm-5.2.
I have to remove dkms module for amdgpu-dkms, and with upstream kernel amdgpu module, gfx803 work fine.

**Comment by tejasraman** [comment]
I’m still having this issue:
![23EF12C6-27AB-42DE-B254-7E65651438A3](https://user-images.githubusercontent.com/96961804/184554625-ba992019-19f0-4667-8c42-52d5b753ee5c.jpeg)
Clinfo
![Uploading 21F42926-5136-4495-A857-856E0D14712A.jpeg…]()
